import React from 'react';
import { FileText, Download, CheckCircle, AlertTriangle, XCircle, Shield } from 'lucide-react';

function IntegrityReport({ report, onClose }) {
    const getRiskColor = (level) => {
        switch (level) {
            case 'low': return 'text-green-400 bg-green-900/20 border-green-700';
            case 'medium': return 'text-yellow-400 bg-yellow-900/20 border-yellow-700';
            case 'high': return 'text-red-400 bg-red-900/20 border-red-700';
            default: return 'text-gray-400 bg-gray-900/20 border-gray-700';
        }
    };

    const getRiskIcon = (level) => {
        switch (level) {
            case 'low': return <CheckCircle className="w-6 h-6" />;
            case 'medium': return <AlertTriangle className="w-6 h-6" />;
            case 'high': return <XCircle className="w-6 h-6" />;
            default: return <Shield className="w-6 h-6" />;
        }
    };

    const downloadReport = () => {
        const reportText = `
EXAM INTEGRITY REPORT
=====================

Exam: ${report.exam}
Student: ${report.student}
Session ID: ${report.sessionId}
Duration: ${report.duration} minutes
Completed: ${new Date(report.timestamp).toLocaleString()}

INTEGRITY SCORE: ${report.integrityScore}/100
RISK LEVEL: ${report.riskLevel.toUpperCase()}

BEHAVIORAL METRICS:
- Tab Switches: ${report.metrics.tabSwitchCount}
- Total Focus Lost: ${report.metrics.totalFocusLostDuration}s
- Face Absent Events: ${report.metrics.faceAbsentCount}
- Gaze Deviations: ${report.metrics.gazeDeviationCount}
- Audio Spikes: ${report.metrics.audioSpikeCount}
- Warnings Shown: ${report.metrics.warningsShown}

VERIFICATION:
Report Hash: ${report.reportHash}
Digital Signature: ${report.reportSignature}

This report is digitally signed and tamper-proof.
Any modification will invalidate the signature.

Generated by ParikshaX Secure Exam Browser
    `.trim();

        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `integrity-report-${report.sessionId}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4 overflow-y-auto">
            <div className="bg-gray-900 border border-gray-700 rounded-2xl max-w-4xl w-full p-8 shadow-2xl my-8">
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <FileText className="w-8 h-8 text-cyan-500" />
                        <h2 className="text-2xl font-bold">Exam Integrity Report</h2>
                    </div>
                    <button
                        onClick={downloadReport}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-700 text-white text-sm font-medium transition-all"
                    >
                        <Download className="w-4 h-4" />
                        Download Report
                    </button>
                </div>

                {/* Overall Score */}
                <div className={`p-6 rounded-xl border mb-6 ${getRiskColor(report.riskLevel)}`}>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            {getRiskIcon(report.riskLevel)}
                            <div>
                                <div className="text-sm opacity-80 uppercase tracking-wider">Overall Risk Level</div>
                                <div className="text-3xl font-bold capitalize">{report.riskLevel}</div>
                            </div>
                        </div>
                        <div className="text-right">
                            <div className="text-sm opacity-80">Integrity Score</div>
                            <div className="text-5xl font-bold">{report.integrityScore}</div>
                            <div className="text-sm opacity-80">out of 100</div>
                        </div>
                    </div>
                </div>

                {/* Exam Details */}
                <div className="grid grid-cols-2 gap-4 mb-6">
                    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                        <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Exam</div>
                        <div className="text-lg font-semibold">{report.exam}</div>
                    </div>
                    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                        <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Student</div>
                        <div className="text-lg font-semibold">{report.student}</div>
                    </div>
                    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                        <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Duration</div>
                        <div className="text-lg font-semibold">{report.duration} minutes</div>
                    </div>
                    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                        <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Completed</div>
                        <div className="text-lg font-semibold">{new Date(report.timestamp).toLocaleString()}</div>
                    </div>
                </div>

                {/* Behavioral Metrics */}
                <div className="mb-6">
                    <h3 className="text-lg font-bold mb-4">Behavioral Metrics</h3>
                    <div className="grid grid-cols-3 gap-4">
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Tab Switches</div>
                            <div className="text-2xl font-bold">{report.metrics.tabSwitchCount}</div>
                        </div>
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Focus Lost</div>
                            <div className="text-2xl font-bold">{report.metrics.totalFocusLostDuration}s</div>
                        </div>
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Face Absent</div>
                            <div className="text-2xl font-bold">{report.metrics.faceAbsentCount}</div>
                        </div>
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Gaze Deviations</div>
                            <div className="text-2xl font-bold">{report.metrics.gazeDeviationCount}</div>
                        </div>
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Audio Spikes</div>
                            <div className="text-2xl font-bold">{report.metrics.audioSpikeCount}</div>
                        </div>
                        <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                            <div className="text-xs text-gray-500 mb-1">Warnings</div>
                            <div className="text-2xl font-bold">{report.metrics.warningsShown}</div>
                        </div>
                    </div>
                </div>

                {/* Verification */}
                <div className="bg-gray-800/50 p-4 rounded-lg border border-gray-700 mb-6">
                    <h3 className="text-sm font-bold mb-3 text-cyan-400">Tamper-Proof Verification</h3>
                    <div className="space-y-2 text-xs font-mono">
                        <div>
                            <span className="text-gray-500">Session ID:</span>
                            <span className="ml-2 text-gray-300">{report.sessionId}</span>
                        </div>
                        <div>
                            <span className="text-gray-500">Report Hash:</span>
                            <span className="ml-2 text-gray-300 break-all">{report.reportHash}</span>
                        </div>
                        <div>
                            <span className="text-gray-500">Digital Signature:</span>
                            <span className="ml-2 text-gray-300 break-all">{report.reportSignature}</span>
                        </div>
                    </div>
                    <p className="text-xs text-gray-500 mt-3">
                        This report is cryptographically signed. Any modification will invalidate the signature.
                    </p>
                </div>

                {/* Disclaimer */}
                <div className="bg-blue-900/20 p-4 rounded-lg border border-blue-700/50 mb-6">
                    <p className="text-sm text-blue-300">
                        <strong>Important:</strong> This report provides behavioral indicators only.
                        It does not constitute proof of cheating. All flagged sessions require human review
                        and consideration of context before any academic action is taken.
                    </p>
                </div>

                <button
                    onClick={onClose}
                    className="w-full py-3 rounded-xl bg-gray-800 hover:bg-gray-700 border border-gray-700 font-bold text-white transition-all"
                >
                    Close Report
                </button>
            </div>
        </div>
    );
}

export default IntegrityReport;
